#!/usr/bin/env ruby

# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'rack'
require 'wovn/reverse_proxy'

Rack::Server.start(
  app: Wovn::ReverseProxy::Wovnrb.new(
    Wovn::ReverseProxy::RackReverseProxy.new
  ),
  Port: 4567
)
